### ISSUE TITLE
Can't compile with rustc 1.3.0-nightly (69ca01256 2015-07-23)

### ISSUE THREAD

**Issue by carlopires** [carllerche/mio-examples#1]
Hi,

I tried to compile this but got this error:

    carlopires@carlo-DH67VR:~/rust/lesson4/mio-examples/ping_pong$ cargo run
     Downloading slab v0.1.1
     Downloading mio v0.4.1
       Compiling libc v0.1.8
       Compiling bytes v0.2.10
       Compiling slab v0.1.1
       Compiling bitflags v0.1.1
       Compiling nix v0.3.9
       Compiling winapi v0.1.23
       Compiling log v0.3.1
       Compiling clock_ticks v0.0.5
       Compiling mio v0.4.1
       Compiling pingpong v0.1.0 (file:///home/carlopires/rust/lesson4/mio-examples/ping_pong)
    src/main.rs:7:18: 7:22 error: unresolved import `bytes::Take`. There is no `Take` in `bytes` [E0432]
    src/main.rs:7 use bytes::{Buf, Take};
                                   ^~~~
    error: aborting due to previous error
    Could not compile `pingpong`.

Rust version:

    carlopires@carlo-DH67VR:~/rust/lesson4/mio-examples/ping_pong$ rustc --version
    rustc 1.3.0-nightly (69ca01256 2015-07-23)

**Comment by carllerche** [comment]
Thanks for the report. I got some feedback that it would be better to work on the example in the mio repo proper, so I moved the example there. I also fixed the issue that you reported, so hopefully it should work now.

The example is here: https://github.com/carllerche/mio/tree/getting-started in the examples/ping_pong directory. Cloning the repo and running `cargo run` in the ping pong directory should work.

Also, I have a PR representing the in progress work, so issues would be best left as comments https://github.com/carllerche/mio/pull/222

Thanks.
